### ISSUE TITLE
Responsive Website

### ISSUE THREAD

**Issue by ghost** [siimple/website#1] opened 2017-02-16 20:48 UTC
The Website for the doc's etc. isn't responsive at all, you should change that.

**Comment by skirsten** [comment] 2017-02-16 21:40
I think the problem is the `width: 1180px;` in the [header](https://github.com/siimple/website/blob/master/_scss/style.scss#L68), [main](https://github.com/siimple/website/blob/master/_scss/style.scss#L102), [contribute](https://github.com/siimple/website/blob/master/_scss/style.scss#L118) and [footer](https://github.com/siimple/website/blob/master/_scss/style.scss#L131) css tags.
It could be changed to `max-width` which should restore the responsiveness of the old siimple page.
I haven't tested it though.

By the way @jmjuanes, thank you very much for siimple 2.0! I'm looking forward to upgrading :D

**Comment by jmjuanes** [comment] 2017-02-18 19:45
Hello @oltmannsdaniel . Nice to hear from you! 

The current website is only temporally. I am finishing the `siimple-layout` module (which contains elements like navbar, footer,...), and that module is responsive. I will update the website with the layout components when it is finished 😄 

And thanks @skirsten ! I really appreciate that you like the new version 🎉 🎉 

If you want to collaborate, you are welcome 😉

**Comment by jmjuanes** [comment] 2018-06-26 09:52
The website is responsive. Closing this issue.

**Closed as completed by jmjuanes** 2018-06-26 09:52 UTC
